# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 153175ec1f3f35e582fea7f647b43f165d70079b7af25036ef33441e9c14cc437bf856dd060d4ba8fb9939373a81fc8c5df3297b80397ce4a3ecab110bf53d9c

test:
  secret_key_base: b92ec71306372aeca1f1479a080c204c669f5e23596a0f6b73e458d418c853db35f31b2232519fc4043940592e1a5e9fd26d7d2c5bb26e471147d76e8a393583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
